Interface:
    TextInput:
        id: textInput
        size_hint:0.5,0.1
        pos_hint: {"center_x":0.5, "center_y":0.6}
    Label:
        id: label
        text: "Nothing"
        size_hint:0.5,0.1
        pos_hint:{"center_x":0.5, "center_y":0.5}
    Button:
        text: "Click Me!"
        size_hint:0.5,0.1
        pos_hint:{"center_x":0.5, "center_y":0.4}
        on_press: root.display_information()